config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#index'
  resources :tweets, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: [:index]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end
  
  def create
    Tweet.create(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.destroy
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
      if tweet.user_id == current_user.id
        tweet.update(tweet_params)
      end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:image,:text).merge(user_id:current_user.id)
  end

  def move_to_index
    redirect_to root_path unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="title">
        <a href="/">
          <% if user_signed_in? %>
            <%= current_user.nickname %>
          <% end %>
          blog
        </a>
      </div>
        <ul class="lists">
          <% if user_signed_in? %>
            <il class="list"><a class="list_name" href="/users/<%= current_user.id %>" >マイページ</a></il>
            <il class="list"><%= link_to "ログアウト", destroy_user_session_path, method: :delete , class: "list_name" %></il>
            <il class="list"><%= link_to "投稿", new_tweet_path , class: "list_name" %></il>
          <% else %>
            <il class="list"><%= link_to "新規登録", new_user_registration_path, class: "list_name" %></il>
            <il class="list"><%= link_to "ログイン", new_user_session_path , class: "list_name" %></il> 
          <% end %>
        </ul>
    </header>

    <%= yield %>
    
    <footer>
    </footer>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="contents_post"> 
 <div class="contents_img">
  <%= image_tag(tweet.image) %>
 </div>
  <p><%= simple_format(tweet.text) %></p>
  <span class="name">
    <a href="/users/<%= tweet.user_id %>", class="post_name">
      <span>投稿者</span><%= tweet.user.nickname %>
    </a>
  </span>
  <div class="more">
    <ul class="more_lists">
      <% if  user_signed_in? && current_user.id == tweet.user_id %>
        <li class="more_list">
          <button>
            <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get , class: "button_name" %>
          </button>
        </li>
        <li class="more_list">
          <button>
            <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete , class: "button_name" %>
          </button>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tweets/create.html.erb
<div class="contents sent">
  <h3>投稿完了しました</h3>
  <%= link_to "トップページに戻る", root_path %>
</div>

app/views/tweets/destroy.html.erb
<div class="contents sent">
  <h3>削除しました</h3>
  <%= link_to "トップページに戻る", root_path %>
</div>

app/views/tweets/edit.html.erb
<div class="contents sent">
  <h3>編集する</h3>
  <%= form_for @tweet do |f| %>
    <div>
      <%= f.label :画像 %>
      <%= f.text_field :image %>
    </div>
    <div>
      <%= f.label :日記 %>
      <%= f.text_area :text, style: 'width: 30%;height: 100px;' %>
    </div>
    <div>
      <%= button_tag type: "submit", class: "btn btn--block" do %>
      更新
      <% end %>
    </div>
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="contents_row" >
    <%= render @tweets%>
    <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents sent">
  <h3>投稿する</h3>
  <%= form_for @tweet do |f| %>
    <div>
      <%= f.label :画像 %>
      <%= f.text_field :image %>
    </div>
    <div>
      <%= f.label :日記 %>
      <%= f.text_area :text, style: 'width: 30%;height: 100px;' %>
    </div>
    <div>
      <%= button_tag type: "submit", class: "btn btn--block" do %>
      投稿
      <% end %>
    </div>
  <% end %>
</div>

app/views/tweets/update.html.erb
<div class="contents sent">
  <h3>編集完了しました</h3>
  <%= link_to "トップページに戻る", root_path %>
</div>

app/views/users/show.html.erb
<div class="contents_row" >
  <h3><%= @nickname %>さんの投稿一覧</h3>
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets) %>
</div>